# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqxEPWWLNjT-X3pRo93K2dDi_7jly85h
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install prophet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from prophet import Prophet
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN

df = pd.read_csv(
    "/content/drive/MyDrive/FitPulse_Milestone1/data/minute_level_data.csv"
)
df["timestamp"] = pd.to_datetime(df["timestamp"])

user_id = df["Id"].iloc[0]
hr_df = df[df["Id"] == user_id][["timestamp", "HeartRate"]]

hr_df = hr_df.rename(columns={
    "timestamp": "ds",
    "HeartRate": "y"
})

model = Prophet(
    daily_seasonality=True,
    weekly_seasonality=True
)

model.fit(hr_df)

forecast = model.predict(model.make_future_dataframe(periods=0))

model.plot(forecast)
plt.show()

model.plot_components(forecast)
plt.show()

features = pd.read_csv(
    "/content/drive/MyDrive/FitPulse_Milestone2/data/tsfresh_features.csv",
    index_col=0
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(
    eps=3.0,        # ⬅️ increased
    min_samples=2
)

clusters = dbscan.fit_predict(X_scaled)
features["cluster"] = clusters
features

features["cluster"] = clusters
features

anomalies = features[features["cluster"] == -1]
anomalies

features.to_csv(
    "/content/drive/MyDrive/FitPulse_Milestone2/data/dbscan_clustered_features.csv"
)

X = features.drop(columns=["cluster"])
y = features["cluster"]

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

plt.figure(figsize=(8, 6))

plt.scatter(
    X_pca[y != -1, 0],
    X_pca[y != -1, 1],
    c="green",
    label="Normal Users",
    s=100
)

plt.scatter(
    X_pca[y == -1, 0],
    X_pca[y == -1, 1],
    c="red",
    label="Anomalous Users",
    s=100,
    marker="x"
)

plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.title("DBSCAN Clustering of Users (TSFresh Features)")
plt.legend()
plt.grid(True)
plt.show()

